### ISSUE TITLE
Bails on source .d.ts files

### ISSUE THREAD

**Issue by ghostdevv** [ghostdevv/extractinator#24]
```
~/code/skeleton/packages/skeleton pnpm extractinator extract src/lib out/
Writing dts files to "/Users/nik/code/skeleton/packages/skeleton/.extractinator/dts-1703336102778"

{
  dts_path: '/Users/nik/code/skeleton/packages/skeleton/.extractinator/dts-1703336102778/actions/Clipboard/additional-svelte-typings.d.d.ts',
  input_path: '/Users/nik/code/skeleton/packages/skeleton/src/lib/actions/Clipboard/additional-svelte-typings.d.ts'
}
file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.3.0/node_modules/extractinator/dist/cli.js:393
      throw new Error(`Unable to find dts path for "${input_path}"`);
            ^

Error: Unable to find dts path for "/Users/nik/code/skeleton/packages/skeleton/src/lib/actions/Clipboard/additional-svelte-typings.d.ts"
    at emit_dts (file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.3.0/node_modules/extractinator/dist/cli.js:393:13)
    at async extractinator (file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.3.0/node_modules/extractinator/dist/cli.js:410:41)
    at async file:///Users/nik/code/skeleton/packages/skeleton/node_modules/.pnpm/extractinator@0.3.0/node_modules/extractinator/dist/cli.js:486:27

Node.js v21.4.0
```

From @niktek - https://github.com/ghostdevv/extractinator/issues/17#issuecomment-1868290452

**Comment by ghostdevv** [comment]
This fix should be released in v`0.3.1`
